# preload = /home/rogue/.config/hypr/Wallpapers/a_painting_of_a_building_with_smoke_coming_out_of_it.png
# wallpaper = , /home/rogue/.config/hypr/Wallpapers/a_painting_of_a_building_with_smoke_coming_out_of_it.png

wallpaper{
    monitor=
    path=/home/rogue/.config/hypr/Wallpapers/a_painting_of_a_building_with_smoke_coming_out_of_it.png
    fit_mode = cover
}
splash = false