# music_directory		"$XDG_MUSIC_DIR"
music_directory		"/home/rogue/Music"

db_file "~/.local/share/mpd/db"
log_file "~/.local/share/mpd/log"
state_file "~/.local/share/mpd/state"
sticker_file "~/.local/share/mpd/sticker.sql"

playlist_directory "~/.local/share/mpd/playlists"
pid_file "~/.local/share/mpd/pid"

#playlist_directory		"$XDG_CONFIG_HOME/mpd/playlists"
#playlist_directory		"~/.mpd/playlists"

#db_file			"$XDG_CACHE_HOME/mpd/database"
#db_file			"~/.mpd/database"

# log_file			"$XDG_CACHE_HOME/mpd/log"
# log_file			"~/.mpd/log"
# pid_file			"$XDG_RUNTIME_DIR/mpd/mpd.pid"
# pid_file			"~/.mpd/pid"

#state_file			"$XDG_STATE_HOME/mpd/state"
#state_file			"~/.mpd/state"

#sticker_file			"$XDG_CACHE_HOME/sticker.sql"
#sticker_file			"~/.mpd/sticker.sql"

#user				"nobody"

bind_to_address		"127.0.0.1"
# # And for Unix Socket
# bind_to_address		"$XDG_RUNTIME_DIR/mpd/socket"
# bind_to_address		"~/.mpd/socket"

port				"6001"
#
# Suppress all messages below the given threshold.  Use "verbose" for
# troubleshooting. Available setting arguments are "notice", "info", "verbose",
# "warning" and "error".
#
#log_level			"notice"
restore_paused "yes"
#
# This setting enables MPD to create playlists in a format usable by other
# music players.
#
#save_absolute_paths_in_playlists	"no"
#

max_output_buffer_size "16384"
auto_update	"yes"
#follow_outside_symlinks	"yes"

#follow_inside_symlinks		"yes"
# database {
#       plugin "simple"
#       path "~/.local/share/mpd/db"
#       cache_directory "~/.local/share/mpd/cache"
# }
#
#music_directory "nfs://fileserver.local/srv/mp3"
#database {
#       plugin "proxy"
#       host "other.mpd.host"
#       port "6600"
#}

# Input #######################################################################
# #
# input {
#         plugin "curl"
# #       proxy "proxy.isp.com:8080"
# #       proxy_user "user"
# #       proxy_password "password"
# }

audio_output {
	type		"pulse"
	name		"pulse"
#	server		"remote_server"		# optional
#	sink		"remote_server_sink"	# optional
#	media_role	"media_role"		#optional
}

## Example "pipe" output:
#
# audio_output {
# 	type		"pipe"
# 	name		"my pipe"
# 	command		"aplay -f cd 2>/dev/null"
# # Or if you're want to use AudioCompress
# 	command		"AudioCompress -m | aplay -f cd 2>/dev/null"
# # Or to send raw PCM stream through PCM:
# 	command		"nc example.org 8765"
# 	format		"44100:16:2"
# }
#
## An example of a null output (for no audio output):
#
#audio_output {
#	type		"null"
#	name		"My Null Output"
#	mixer_type      "none"			# optional
#}
#
###############################################################################


# Normalization automatic volume adjustments ##################################
#
# This setting specifies the type of ReplayGain to use. This setting can have
# the argument "off", "album", "track" or "auto". "auto" is a special mode that
# chooses between "track" and "album" depending on the current state of
# random playback. If random playback is enabled then "track" mode is used.
# See <https://wiki.hydrogenaud.io/index.php?title=Replaygain> for
# more details about ReplayGain.
# This setting is off by default.
#
#replaygain			"album"
#
###############################################################################

# Character Encoding ##########################################################
#
# If file or directory names do not display correctly for your locale then you
# may need to modify this setting.
#
#filesystem_charset		"UTF-8"
#
###############################################################################